version: '3'

services:
  
  gunicorn:
    build: .
    command: gunicorn -b 0.0.0.0:8018 --access-logfile - --reload "gateway:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    ports:
      - '8010:8010'
    expose:
      - "8010"
    network_mode: "host"
