version: '3'

services:

  gunicorn:
    build: .
    command: gunicorn -b 0.0.0.0:80 wsgi
    environment:
      PYTHONUNBUFFERED: 'true'
    ports:
      - '80:80'
    expose:
      - "80"
    network_mode: "host"